version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-docker
    user: root  # temporarily run as root to avoid docker.sock permission issues
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
