FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && apt-get install -y docker.io

# Create docker group if it doesn't exist and add jenkins
RUN groupadd -f docker \
    && usermod -aG docker jenkins

USER jenkins
