FROM jenkins/jenkins:lts

USER root

# Install Docker inside Jenkins container
RUN apt-get update && apt-get install -y docker.io

# Allow Jenkins user to access Docker
RUN usermod -aG docker jenkins

USER jenkins

