pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t simple-app ./simple-app'
                }
            }
        }

        stage('Run App Container') {
            steps {
                script {
                    sh 'docker run --rm simple-app'
                }
            }
        }
    }
}
