pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/onkar69483/DevOpsLab3.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t simple-app ./simple-app'
                }
            }
        }

        stage('Run App Container') {
            steps {
                script {
                    sh 'docker run --rm simple-app'
                }
            }
        }
    }
}
