apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-content
data:
  index.html: |
    <html>
      <head>
        <title>My Apache2 Server</title>
      </head>
      <body>
        <h1>Hello from Kubernetes Apache2!</h1>
        <p>This is a custom HTML page served via ConfigMap.</p>
      </body>
    </html>

---
# Deployment for Apache2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4       # Official Apache2 image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-content
          mountPath: /usr/local/apache2/htdocs/   # Apache document root
      volumes:
      - name: apache-content
        configMap:
          name: apache-content

---
# Service to expose Apache2
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082   
